language: go
os:
  - linux
  - osx
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x

before_install:
  - go get github.com/mattn/goveralls
# Travis tries to run broken third-party tests during install, skip that
install:
  - true
script:
  - go test -v
  - go build
after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
