version: build-{build}.{branch}
platform:
  - x64
  - x86

clone_folder: c:\gopath\src\github.com\casept\mfp-dl
environment:  
  GOPATH: c:\gopath

install:  
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
build_script:
  - go build -o buildOutput/mfp-dl -i .
artifacts:
  path: buildOutput/mfp-dl
  name: binary
