
[[dependencies]]
  branch = "master"
  name = "github.com/bogem/id3v2"

[[dependencies]]
  branch = "master"
  name = "github.com/mmcdole/gofeed"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/cheggaaa/pb.v1"
